ComprasBundle\Entity\ComprasEnc:
    type: entity
    table: ComprasEnc
    repositoryClass: ComprasBundle\Repository\ComprasEncRepository
    id:
        codigoCompraEnc:
            type: integer
            id: true
            unique: true
            generator:
                strategy: IDENTITY
            column: codigo_compra_enc
    fields:
        numFactura:
            type: string
            length: '10'
            column: num_factura
        fechaCompra:
            type: datetime
            column: fecha_compra
        codigoProveedor:
            type: integer
            column: codigo_proveedor
        observacion:
            type: string
            length: '100'
            nullable: true
            column: observacion
        total:
            type: decimal
            precision: '9'
            scale: '18'
        codigoEmpleado:
            type: integer
            column: codigo_empleado
        fechaIngreso:
            type: datetime
            column: fecha_ingreso
    manyToOne:
        proveedor:
            targetEntity: \MantenimientosBundle\Entity\Proveedor
            inversedBy: comprasEnc
            joinColumn:
                name: codigo_proveedor
                referencedColumnName: codigo_proveedor
        empleado:
            targetEntity: \MantenimientosBundle\Entity\Empleados
            inversedBy: comprasEnc
            joinColumn:
                name: codigo_empleado
                referencedColumnName: codigo_empleado
        
    lifecycleCallbacks: {  }
