ComprasBundle\Entity\ComprasEnc:
    type: entity
    table: null
    repositoryClass: ComprasBundle\Repository\ComprasEncRepository
    id:
        codigoCompraEnc:
            type: integer
            nullable: false
            column: codigo_compra_enc
            id: true
            generator:
                strategy: IDENTITY
    fields:
        
        numFactura:
            type: string
            length: '10'
            column: num_factura
        fechaCompra:
            type: date
            column: fecha_compra
        codigoProveedor:
            type: integer
            column: codigo_proveedor
        observacion:
            type: string
            length: '100'
        total:
            type: decimal
            precision: '18'
            scale: '9'
            column: total
    lifecycleCallbacks: {  }
