ComprasBundle\Entity\ComprasEnc:
    type: entity
    table: null
    repositoryClass: ComprasBundle\Repository\ComprasEncRepository
    id:
        codigoCompraEnc:
            type: integer
            id: true
            unique: true
            column: codigo_compra_enc
            generator:
                strategy: IDENTITY
    fields:
        
        numFactura:
            type: string
            length: '10'
            column: num_factura
        fechaCompra:
            type: datetime
            column: fecha_compra
        codigoProveedor:
            type: integer
            column: codigo_proveedor
        observacion:
            type: string
            length: '100'
            nullable: true
        total:
            type: decimal
            precision: '18'
            scale: '9'
    manyToOne:
        proveedor:
            targetEntity: \MantenimientosBundle\Entity\Proveedor
            inversedBy: ComprasEnc
            joinColumn:
                name: codigo_proveedor
                referencedColumnName: codigo_proveedor 
    lifecycleCallbacks: {  }
