ComprasBundle\Entity\Compras_Enc:
    type: entity
    table: null
    repositoryClass: ComprasBundle\Repository\Compras_EncRepository
    id:
        codigoCompraEnc:
            type: integer
            unique: true
            column: codigo_compra_enc
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numFactura:
            type: string
            length: '10'
            column: num_factura
        fechaCompra:
            type: datetime
            column: fecha_compra
        codigoProveedor:
            type: integer
            column: codigo_proveedor
        observacion:
            type: string
            length: '100'
            nullable: true
        total:
            type: decimal
            precision: '18'
            scale: '9'
    lifecycleCallbacks: {  }
