ComprasBundle\Entity\Compras_Det:
    type: entity
    table: null
    repositoryClass: ComprasBundle\Repository\Compras_DetRepository
    id:
        codigoCompraDet:
            type: integer
            column: codigo_compra_det
            unique: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        
        numFactura:
            type: string
            length: '10'
            column: num_factura
        codigoProducto:
            type: integer
            column: codigo_producto
        cantidad:
            type: integer
        bDocena:
            type: boolean
            nullable: true
            column: b_docena
        costo:
            type: decimal
            precision: '18'
            scale: '9'
            nullable: true
        codigoCompraEnc:
            type: integer
            column: codigo_compra_enc
    lifecycleCallbacks: {  }
