mantenimientos:
    path:     /mantenimientos
    defaults: { _controller: MantenimientosBundle:Catalogos:index }
    
agencias:
    path:     /mantenimientos/agencias
    defaults: { _controller: MantenimientosBundle:Agencias:index }
    
addagencia:
    path:     /mantenimientos/agencias/add
    defaults: { _controller: MantenimientosBundle:Agencias:add } 

rubros:
    path:     /mantenimientos/rubros
    defaults: { _controller: MantenimientosBundle:Rubros:index }
    
addrubros:
    path:     /mantenimientos/rubros/add
    defaults: { _controller: MantenimientosBundle:Rubros:add } 

categorias:
    path:     /mantenimientos/categorias
    defaults: { _controller: MantenimientosBundle:Categorias:index }
    
addcategorias:
    path:     /mantenimientos/categorias/add
    defaults: { _controller: MantenimientosBundle:Categorias:add }
    
empleados:
    path:     /mantenimientos/empleados
    defaults: { _controller: MantenimientosBundle:Empleados:index }
addempleado:
    path:     /mantenimientos/empleados/add
    defaults: { _controller: MantenimientosBundle:Empleados:add }
    
proveedores:
    path:     /mantenimientos/proveedores
    defaults: { _controller: MantenimientosBundle:Proveedores:index }

addproveedor:
    path:     /mantenimientos/proveedores/add
    defaults: { _controller: MantenimientosBundle:Proveedores:add }

productos:
    path:     /mantenimientos/productos
    defaults: { _controller: MantenimientosBundle:productos:index }
addproducto:
    path:     /mantenimientos/productos/add
    defaults: { _controller: MantenimientosBundle:productos:add }

