mantenimientos_homepage:
    path:     /
    defaults: { _controller: MantenimientosBundle:Default:index }
    
mantenimientos:
    path:     /mantenimientos
    defaults: { _controller: MantenimientosBundle:Catalogos:index }
