ventas:
    path:   /ventas
    defaults: { _controller: VentasBundle:Ventas:index } 

editventa:
    path:     /ventas/edit/{codigoVentaEnc}
    defaults: {_controller: VentasBundle:Ventas:edit }
    
addventa:
    path:   /ventas/add
    defaults: { _controller: VentasBundle:Ventas:add }
    

