<?php

namespace ComprasBundle\Repository;

/**
 * Compras_EncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compras_EncRepository extends \Doctrine\ORM\EntityRepository
{
}
