<?php

namespace ComprasBundle\Repository;

/**
 * ComprasDetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprasDetRepository extends \Doctrine\ORM\EntityRepository
{
}
