<?php

namespace ComprasBundle\Repository;

/**
 * ComprasEncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprasEncRepository extends \Doctrine\ORM\EntityRepository
{
}
