seguridad:
    resource: "@SeguridadBundle/Resources/config/routing.yml"
    prefix:   /

mantenimientos:
    resource: "@MantenimientosBundle/Resources/config/routing.yml"
    prefix:   /

tablero:
    resource: "@TableroBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /
 
app:
    resource: '@AppBundle/Controller/'
    type: annotation
