movimientos:
    resource: "@MovimientosBundle/Resources/config/routing.yml"
    prefix:   /

compras:
    resource: "@ComprasBundle/Resources/config/routing.yml"
    prefix:   /

ventas:
    resource: "@VentasBundle/Resources/config/routing.yml"
    prefix:   /

productos:
    resource: "@ProductosBundle/Resources/config/routing.yml"
    prefix:   /

seguridad:
    resource: "@SeguridadBundle/Resources/config/routing.yml"
    prefix:   /

mantenimientos:
    resource: "@MantenimientosBundle/Resources/config/routing.yml"
    prefix:   /

tablero:
    resource: "@TableroBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /
 
app:
    resource: '@AppBundle/Controller/'
    type: annotation
