<?php

namespace VentasBundle\Repository;

/**
 * VentasEncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentasEncRepository extends \Doctrine\ORM\EntityRepository
{
}
