<?php

namespace MantenimientosBundle\Repository;

/**
 * AgenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
