<?php

namespace MantenimientosBundle\Repository;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasRepository extends \Doctrine\ORM\EntityRepository {

    public function findByOneIdJoinedToRubro($codigoRubro) {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT c,r FROM MantenimientosBundle:Categorias c
                                JOIN c.rubros r
                                WHERE c.codigoCategoria = :id')
                ->setParameter('id', $codigoRubro);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
