<?php

namespace MantenimientosBundle\Repository;

/**
 * EmpleadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadosRepository extends \Doctrine\ORM\EntityRepository
{
}
