<?php

namespace MantenimientosBundle\Repository;

/**
 * ProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosRepository extends \Doctrine\ORM\EntityRepository {

       
     public function findProductos() {
        $query = $this->getEntityManager()
                        ->createQuery(
                            'SELECT p, c FROM MantenimientosBundle:Productos p
                             JOIN p.categorias c '
                        );

        try {
            return $query->getResult();//getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    
    
    

}
