<?php

namespace MantenimientosBundle\Repository;

/**
 * RubrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubrosRepository extends \Doctrine\ORM\EntityRepository
{
}
