<?php

namespace ProductosBundle\Repository;

/**
 * KardexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KardexRepository extends \Doctrine\ORM\EntityRepository
{
}
