<?php

namespace ProductosBundle\Repository;

/**
 * productosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productosRepository extends \Doctrine\ORM\EntityRepository
{
}
