compras:
    path:     /compras
    defaults: { _controller: ComprasBundle:Compras:index }
vercompra:
    path:     /compras/vercompra/{codigoCompraEnc}
    defaults: { _controller: ComprasBundle:Compras:vercompra }
addcompra:
    path:      /compras/add
    defaults: { _controller: ComprasBundle:Compras:add }
    
addcompraenc:
    path:      /compras/add
    defaults: { _controller: ComprasBundle:Compras:add }


editcompra:
    path:     /compras/edit/{codigoCompraEnc}
    defaults: {_controller: ComprasBundle:Compras:edit}
    
    

    