compras:
    path:     /compras
    defaults: { _controller: ComprasBundle:Compras:index }
vercompra:
    path:     /compras/vercompra/{codigoComprasEnc}
    defaults: { _controller: ComprasBundle:Compras:vercompra }
