MantenimientosBundle\Entity\Agencia:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\AgenciaRepository
    id:
        codigoAgencia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_agencia
            generator:
                strategy: IDENTITY
    fields:
        nombreAgencia:
            type: string
            length: '100'
            nullable: true
            column: nombre_agencia
        telefono:
            type: string
            length: '10'
            nullable: true
        descripcion:
            type: string
            length: '100'
            nullable: true
    oneToMany:
        VentasEnc:
            targetEntity: \VentasBundle\Entity\VentasEnc
            mappedBy: agencia
    lifecycleCallbacks: {  }
