MantenimientosBundle\Entity\Agencia:
    type: entity
    table: agencia
    repositoryClass: MantenimientosBundle\Repository\AgenciaRepository
    codigoAgencia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: false
            column: codigo_agencia
            generator:
                strategy: IDENTITY
    fields:
        nombreAgencia:
            type: string
            length: '100'
            column: nombre_agencia
        telefono:
            type: string
            length: '10'
            nullable: true
        descripcion:
            type: string
            length: '100'
            nullable: true
    lifecycleCallbacks: {  }
