MantenimientosBundle\Entity\Categorias:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\CategoriasRepository
    id:
        codigoCategoria:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_categoria
            generator:
                strategy: IDENTITY
    fields:
        nombreCategoria:
            type: string
            length: '100'
            column: nombre_categoria
        codigoRubro:
            type: integer
            unique: false
            column: codigo_rubro
    lifecycleCallbacks: {  }
