MantenimientosBundle\Entity\Empleados:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\EmpleadosRepository
    id:
        codigoEmpleado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_empleado
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            length: '50'
        apellidos:
            type: string
            length: '50'
        dui:
            type: string
            length: '15'
            unique: true
        direccion:
            type: string
            length: '100'
            nullable: true
        telefono:
            type: string
            length: '10'
            nullable: true
    oneToMany:
        ventasEnc:
            targetEntity: \VentasBundle\Entity\VentasEnc
            mappedBy: vendedor 
    lifecycleCallbacks: {  }
