MantenimientosBundle\Entity\Productos:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\ProductosRepository
    id:
        codigoProducto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            unique: true
            column: codigo_producto
            generator:
                strategy: IDENTITY
    fields:
        codigoArticulo:
            type: string
            length: '200'
            column: codigo_articulo
        codigoCategoria:
            type: integer
            column: codigo_categoria
        nombre:
            type: string
            length: '200'
        precioCosto:
            type: decimal
            precision: '18'
            scale: '9'
            column: precio_costo
        precioVenta:
            type: decimal
            precision: '18'
            scale: '9'
            nullable: true
            column: precio_venta
        ganancia:
            type: decimal
            precision: '8'
            scale: '2'
            nullable: true
        existencia:
            type: integer
        existenciaPrevia:
            type: integer
            nullable: true
            column: existencia_previa
        docena:
            type: decimal
            precision: '18'
            scale: '9'
            nullable: true
        bPrecioDocena:
            type: boolean
            column: b_precio_docena
            nullable: true
            
        bActivo:
            type: string
            length: '1'
            nullable: true
            column: b_activo
    manyToOne:
        categorias:
            targetEntity: Categorias
            inversedBy: productos
            joinColumn:
                name: codigo_categoria
                referencedColumnName: codigo_categoria
    lifecycleCallbacks: {  }
