MantenimientosBundle\Entity\Proveedor:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\ProveedorRepository
    id:
        codigoProveedor:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_proveedor
            generator:
                strategy: IDENTITY
    fields:
        nombreProveedor:
            type: string
            length: '100'
            column: nombre_proveedor
        telefono:
            type: string
            length: '10'
            nullable: true
        contacto:
            type: string
            length: '50'
            nullable: true
    lifecycleCallbacks: {  }
