MantenimientosBundle\Entity\Rubros:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\RubrosRepository
    id:
        codigoRubro:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: codigo_rubro
            generator:
                strategy: IDENTITY
    fields:
        nombreRubro:
            type: string
            length: '100'
            column: nombre_rubro
    lifecycleCallbacks: {  }
