MantenimientosBundle\Entity\Rubros:
    type: entity
    table: null
    repositoryClass: MantenimientosBundle\Repository\RubrosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        codigoRubro:
            type: integer
            unique: true
            column: codigo_rubro
        nombreRubro:
            type: string
            length: '100'
            column: nombre_rubro
    lifecycleCallbacks: {  }
